//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attocaert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public tbl_invoice()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int in_id { get; set; }
        public Nullable<int> in_fk_user { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<double> in_totalbill { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
