//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attocaert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_invoice = new HashSet<tbl_invoice>();
        }
    
        public int U_id { get; set; }
        public string u_name { get; set; }
        public string u_contact { get; set; }
        public string u_password { get; set; }
    
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
    }
}
