//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attocaert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int o_id { get; set; }
        public Nullable<int> o_fk_pro { get; set; }
        public Nullable<int> o_fk_invoice { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<int> o_qty { get; set; }
        public Nullable<double> o_bill { get; set; }
        public Nullable<int> o_unitprice { get; set; }
    
        public virtual tbl_invoice tbl_invoice { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
