//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attocaert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public tbl_product()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public Nullable<double> pro_price { get; set; }
        public string pro_desc { get; set; }
        public string pro_image { get; set; }
    
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
